### ISSUE TITLE
Double page reader needs a way to offset by one page. 

### ISSUE THREAD

**Issue by Ironkeroro** [MinoLiu/Let-s-panda#15]
Double page needs a way to offset by one page. If a gallery has its pages misaligned there is no way to correct it. (odds on evens) ie. a manga starts with a single page but because of cover pages the single page gets considered a double.

**Comment by MinoLiu** [comment]
Hi Ironkeroro,

I made a new button to do this feature.
![image](https://user-images.githubusercontent.com/17308188/194745623-fd3fa6bb-5c03-4174-95a2-bc11270307f0.png)
enjoy :) !
