### ISSUE TITLE
Error: There are some issues on the script

### ISSUE THREAD

**Issue by TheBaddest** [MinoLiu/Let-s-panda#17]
![image](https://user-images.githubusercontent.com/12594022/196772342-5fd80ff1-59da-4688-bf82-2f82de309ce3.png)
was trying to download images on exh  and this message showed up.

**Comment by MinoLiu** [comment]
Does it always happen?
I will check this issue later.

**Comment by TheBaddest** [comment]
Does not always happen, only on some titles. The error showed up on g/2354511/7702fb8169. 

A different title didn't show any error messages at all, just stuck at "start downloading" after clicking "download archive" and did not actually download images. Another title is stuck at "downloading 6/7 images" and did not finish the download after hours of waiting or restarting the download.

**Comment by MinoLiu** [comment]
The issue is caused by the url not ending with "/".
I fixed the matching strings and it should work fine now.
But {stuck at "downloading 6/7 images"} this is the network issue, I cannot fix it.
