### ISSUE TITLE
Problem with the image charge

### ISSUE THREAD

**Issue by Mokkita** [MinoLiu/Let-s-panda#22]
loading 1 page of images but some just keep loading and nothing updates in some galleries it loads the images without problem but in others the wheel keeps spinning.

normally it works without problem

**Comment by MinoLiu** [comment]
Yes, it seems to be a network issue, 
because too many images are loaded at the same time.
I will find the time to fix it.

**Comment by MinoLiu** [comment]
Hi @Mokkita ,
I made some changes to the viewer mode in the dev branch.
https://raw.githubusercontent.com/MinoLiu/Let-s-panda/dev/src/main.js

I will test it for a while.
If there is no bug, I will publish the enhancement.

**Comment by Mokkita** [comment]
Okay let me try it and let you know if I find any problems.

**Comment by MinoLiu** [comment]
The main reason is that the image is stuck in the network.
This issue still exists and reducing the "threading" could reduce the issue.

This patch will read the pictures in order, and add the timeout for 10s, 
which will normally reduce the problems you mentioned.
