### ISSUE TITLE
Any possible problems with the viewer?

### ISSUE THREAD

**Issue by Mokkita** [MinoLiu/Let-s-panda#26]
Well I have the perk that increases the preview images to 100 and when I open 2 or 3 tabs I fill the limit of images when at most it would only be 300 images.

I do not know if it is a problem that loads 2 times each image or something else.

**Comment by MinoLiu** [comment]
I'm sorry Mokita, I don't understand what your problem is.
Can you explain more to me?
Also is it normal for the preview image to be below 100?
