### ISSUE TITLE
Temp IP ban drom downloading

### ISSUE THREAD

**Issue by saintmichael95** [MinoLiu/Let-s-panda#27]
Got a temporary IP ban from downloading too much. (A couple galleries totalling about 1500 images.) You should probably let people know that use of the download feature could result in a ban. 
![Screenshot 2023-10-07 152837](https://github.com/MinoLiu/Let-s-panda/assets/26660027/bb12f86c-d3f7-404e-891b-2807de7ff2e3)

**Comment by MinoLiu** [comment]
Thanks for the information, I will try to add a warning for that.
