### ISSUE TITLE
No image preview in firefox

### ISSUE THREAD

**Issue by Mokkita** [MinoLiu/Let-s-panda#29]
only comes out loading and nothing else no matter if I change the mode to 1 page or all pages.

![imagen](https://github.com/MinoLiu/Let-s-panda/assets/135760477/3ff6379c-9a93-44fb-93bd-c96f7c3bb1dd)

**Comment by MinoLiu** [comment]
Hi @Mokkita ,
I fixed this issue 10 hours ago, could you help to update and recheck it?
If it still doesn't work, let me know.
Thanks!

**Comment by Mokkita** [comment]
yes, everything works fine
thank you very much for updating
