### ISSUE TITLE
some issue in the script

### ISSUE THREAD

**Issue by HarutaRX** [MinoLiu/Let-s-panda#36]
<img width="324" alt="屏幕截图 2024-10-25 171401" src="https://github.com/user-attachments/assets/1a03d276-46ca-4e4c-8e9d-a0a634470da7">

When I click download, a prompt like this pops up.

**Comment by MinoLiu** [comment]
I would check later

**Comment by MinoLiu** [comment]
I fixed it in v0.2.20.
If the issue happens again, please let me know thanks.

**Comment by HarutaRX** [comment]
thx!The script can run now！
