### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Ayonig** [MinoLiu/Let-s-panda#38]
I tried the solution given on the bottom but i still cant, im on mobile so i dont think i can use chrome mobile to add violentmonkey. So i use wiki browser
![Screenshot_2024-10-30-16-36-01-57_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/bd4b31af-3cbd-48cc-9a69-9e3697676801)

**Comment by MinoLiu** [comment]
#7 
Hi, have you ever accessed exhentai before?
If not, this might be because your account doesn't the permission to access.

**Comment by Ayonig** [comment]
I haven't, so how can i get the access

**Comment by MinoLiu** [comment]
I don't know either, sorry.
