### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by OtakuSaiKo** [MinoLiu/Let-s-panda#7]
Login failed: Please direct visit forums and log in, the reCaptcha has been enabled.

I have login in to forums already but the same issue appears. What should I do to close the reCaptcha?

**Comment by Sean2525** [comment]
Did you click the blue button? If it is not working that means your account does not have the permission to visit ex.

**Comment by MultiAFAL** [comment]
> Did you click the blue button? If it is not working that means your account does not have the permission to visit ex.

My account has been registered for about a year now, and I've followed the steps to get the sad panda.

Also, the first few tries were met with a "Login Success; you will be redirected in 3 seconds", but instead puts me back into the sad panda section. After a few more tries with no success, it eventually just straight up gave me the "Login Failed; please direct visit forums" message, even thought I have already logged in.

I also pressed the blue button and tried to login again, didn't work, in case it helps to know this.

**Comment by Sean2525** [comment]
@MultiAFAL Can you provide your browser(include version) and plugin manager(e.g. Tampermonkey), I have to reproduce this bug to fix it.

**Comment by Sean2525** [comment]
Currently, I am trying to reproduce this bug.
But
Chrome(v91.0.4472.114) with Tampermonkey(v4.13) - works fine.
Firefox(v89.0.2) with Violentmonkey(v2.13.0) - works fine too.

**Comment by nyanitsu** [comment]
> Login failed: Please direct visit forums and log in, the reCaptcha has been enabled.

I am having the same issue. After I put my credentials and press login, it tells me to visit the forums and login. I logged in and went back to my exhentai login tab and pressed the button it told me to but all it does is reload the entire age and i end up back at the initial login screen. Tried multiple times but the result is same.

I used chrome v91.0.4472.114 and tampermonkey v4.13. Also I disabled adblock and other extensions except tampermonkey incase if thats causing the issue. I tried the latest violentmonkey extension as well after i couldnt access with tampermonkey but same result.

My ehentai account is about 3 years old now.

**Comment by Sean2525** [comment]
@nyanitsu 
I tried these steps:
1. Login failed several times to get reCaptcha.
2. Go to the forum to solve reCaptcha and log in.
3. Go back to exhentai and click the blue button.
4. Successful access to exhentai.
I have no idea, please provide more information
1. Have you ever access exhentai before? 
if so, please clear all cookies (forum,exhentai,e-hentai) then do it again or use another browser(e.g. edge, firefox).
2. Are you using this script for the first time or have you used it before and only recently had problems.

**Comment by MultiAFAL** [comment]
> @MultiAFAL Can you provide your browser(include version) and plugin manager(e.g. Tampermonkey), I have to reproduce this bug to fix it.
> And have you ever get into the "EX" before?
> Because the date of registration is not the only rule. I also have an account that can't get into "EX" that has been registered for 3 years.

Sorry for the late reply, but no, I’ve never been to EX before. It’s my first time, and I’ve tried multiple different browsers (Google, Microsoft Edge, Opera GX) but it’s my first time using this plugin and I’m using it currently on the latest version of Google and Tampermonkey.

Not to mention I’ve tried erasing my cookies when trying to get in as well. Up to no avail.

I’ll try a few more times and update my current situation.

**Comment by MultiAFAL** [comment]
![https___exhentai org - Google Chrome 26_06_21 11_27_17 AM_LI](https://user-images.githubusercontent.com/86432453/123500726-a4892800-d672-11eb-8b9f-f0ebcebd07eb.jpg)

Here's a screenshot of the problem at hand.

**Comment by nyanitsu** [comment]
@Sean2525 
>     1. Have you ever access exhentai before?
>        if so, please clear all cookies (forum,exhentai,e-hentai) then do it again or use another browser(e.g. edge, firefox).
> 
>     2. Are you using this script for the first time or have you used it before and only recently had problems.

No, I have never accessed exhentai before. Also I did clear my cookies regardless.

No, I have not used this script before. This is my first time using it. However, I did try similar scripts before(from github) but none of them worked. So i think my account is probably blocked from accessing ex.

**Comment by Sean2525** [comment]
Sadly, I think your account has no permission to access ex,
There is teaching on some forums, but I don't know how the exactly mechanism works either.
As I known Asia IP cannot get the permission.
